### ISSUE TITLE
проблема с сылками на изображения в теге img

### ISSUE THREAD

**Issue by DenisTolmachev** [DenisTolmachev/wine-store-wp#2]
Проблема с сылками на изображения в теге img.
For exаmple: `<img class="mail" src="images/mail.png" alt="">`
ни в каких вариациях пути к картинке какие я знаю, изображение не отрисовывается

**Comment by DenisTolmachev** [comment]
это кусок кода из footer.php

**Comment by VladimirTolmachev1** [comment]
Проблема решена. Я добавил функцию get_image_path.
Пример использвания:
https://github.com/DenisTolmachev/wine-store-wp/blob/d9ca93f376557ac6f779cc94399477aa77eefa43/wp-content/themes/wine-store-wp/footer.php#L10

**Comment by DenisTolmachev** [comment]
Ты только в футере исправил? Надо по ходу везде пройтись.
