### ISSUE TITLE
Новостной плагин

### ISSUE THREAD

**Issue by DenisTolmachev** [DenisTolmachev/wine-store-wp#3]
Нашел новостной плагин, хорошо стал, легко настраивать шорт кодами, почти идеален по дизайнерской задумке, потребует минимум css правок. Одна проблемма, при создании новости превью выводится корректно, но после нажатия на read more, появляется пустая страница. путь к посту автоматически создается вникуда. Проверял на стандартніх темах, там все норм. Посмотри как будет время, может что то я не доглядел.

**Comment by VladimirTolmachev1** [comment]
Проблема была решена. Закрываю эту задачую
